minecraft:
  local_data: "$HOME/minecraft-data"
  s3_bucket:  "<YOUR_S3_BUCKET_NAME>"
  server:
    memory:       "1500M"
    online_mode:  false
    port:         25565

teamspeak:
  local_data: "$HOME/teamspeak-data"
  s3_bucket:   "<YOUR_S3_BUCKET_NAME>"
